### ISSUE TITLE
Outline of Presentation

### ISSUE THREAD

**Issue by mathematicalmichael** [mathematicalmichael/thesis#82]
# Part 1: Introduction / Preliminaries / The Big Picture: 10 minutes

## 1a. Inverse Problems + Measure Theory 101

- [ ] what question are we trying to answer?

- [ ] how are we going to perform an experiment to do so?

- [ ] what did the experiment result in? describe the trends, different lines on the plot

- [ ] what are the implications of the results we got? what should I take away from this?

---

## 1b. Comparison to Classical Approaches: A Philosophical Distinction

- [ ] what question are we trying to answer?

- [ ] how are we going to perform an experiment to do so?

- [ ] what did the experiment result in? describe the trends, different lines on the plot

- [ ] what are the implications of the results we got? what should I take away from this?

---
---

# Part 2: The MUD Point: 25 minutes

## 2a. Theory of Regularization

- [ ] what question are we trying to answer?

- [ ] how are we going to perform an experiment to do so?

- [ ] what did the experiment result in? describe the trends, different lines on the plot

- [ ] what are the implications of the results we got? what should I take away from this?

---

## 2b. Linear Example: Contours

- [ ] what question are we trying to answer?

- [ ] how are we going to perform an experiment to do so?

- [ ] what did the experiment result in? describe the trends, different lines on the plot

- [ ] what are the implications of the results we got? what should I take away from this?

---

## 2c. High-D Linear Example, Connect Dimension + Rank

- [ ] what question are we trying to answer?
How do the methods compare in higher dimensions?
- [ ] how are we going to perform an experiment to do so?

- [ ] what did the experiment result in? describe the trends, different lines on the plot

- [ ] what are the implications of the results we got? what should I take away from this?

---

## 2d. Forming a QoI from Data

- [ ] what question are we trying to answer?

- [ ] how are we going to perform an experiment to do so?

- [ ] what did the experiment result in? describe the trends, different lines on the plot

- [ ] what are the implications of the results we got? what should I take away from this?

---

## 2e. Nonlinear Example(s)

- [ ] what question are we trying to answer?

- [ ] how are we going to perform an experiment to do so?

- [ ] what did the experiment result in? describe the trends, different lines on the plot

- [ ] what are the implications of the results we got? what should I take away from this?

---
---

# Part 3: Extensions, Future Work: 15 minutes

## 3a. Skewness has an impact. PDE OED Example with focus on the geometry

- [ ] what question are we trying to answer?

- [ ] how are we going to perform an experiment to do so?

- [ ] what did the experiment result in? describe the trends, different lines on the plot

- [ ] what are the implications of the results we got? what should I take away from this?

---

## 3b. Related to distinct information, and the primary sources of error... we present... Iteration!
Some situations may warrant an iterative approach, which requires a bit of reframing in thinking about the problem but poses some real benefits for on-line learning, cheap inference.

- [ ] what question are we trying to answer?

- [ ] how are we going to perform an experiment to do so?

- [ ] what did the experiment result in? describe the trends, different lines on the plot

- [ ] what are the implications of the results we got? what should I take away from this?

---

3c. Code. Ambitions. Current State.

- [ ] what question are we trying to answer?

- [ ] how are we going to perform an experiment to do so?

- [ ] what did the experiment result in? describe the trends, different lines on the plot

- [ ] what are the implications of the results we got? what should I take away from this?

**Comment by mathematicalmichael** [comment]
# 2a 


---
# 2a 


# 2b


# 2c


# 2d


# 2e


---

# 3a
How do choices about the questions we ask (the QoI we use) impact the answers we are able to get? 
Can we construct QoI's (from a same set of available measurements) which are in some sense "better" than others?

# 3b
How can we be clever about the central limitations of this approach (the estimation of high-dimensional distributions). 

# 3c
How does one guarantee the integrity of novel computational mathematics research and make it accessible to the broader public?

**Comment by mathematicalmichael** [comment]
# 3b Iteration

By dimension = 10, you'll want about a million samples to well-approximate a normal, and that's not even a measure of global accuracy, that's just near the mean, and for straightforward Gaussian densities.
